<?php

/**
 * @file
 * Contains disclaimer.module.
 */

use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function disclaimer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the disclaimer module.
    case 'help.page.disclaimer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test task for PHP/DRUPAL candidates.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function disclaimer_theme() {
  return [
    'block__views_block__disclaimer_block_1' => [
      'render element' => 'elements',
      'base hook' => 'block',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 *
 * @param array $attachments
 */
function disclaimer_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'disclaimer/js-cookie';
  $attachments['#attached']['library'][] = 'disclaimer/global-scripts';
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * @param $variables
 */
function disclaimer_preprocess_page(&$variables) {
  $route_match = \Drupal::routeMatch();

  if ($route_match->getRouteName() === 'entity.node.canonical') {
    /** @var \Drupal\node\NodeInterface $node */
    $node = $route_match->getParameter('node');

    if ($node instanceof NodeInterface) {
      $variables['#attached']['drupalSettings']['nodeId'] = $node->id();
    }
  }
}
